/*
 * Copyright (c) 2026 Element Creations Ltd. / FluffyBeep
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
 * Please see LICENSE files in the repository root for full details.
 */

package io.element.android.libraries.matrix.impl.bridgelauncher

/**
 * Extracts platform user IDs and phone numbers from Matrix IDs (MXIDs) generated by bridges.
 *
 * WhatsApp bridge generates two types of user identifiers:
 * - Phone numbers: @whatsapp_5491112345678:server -> "5491112345678"
 * - LIDs (Linked Identity): @whatsapp_lid-171631574052876:server -> null (Internal Meta identifier, not a phone number)
 */
object BridgeIdParser {

    private val WA_LID_REGEX = Regex("""@whatsapp_lid-\d+:""")
    private val WA_PHONE_REGEX = Regex("""@whatsapp_(\d{7,15}):""")
    private val IG_REGEX = Regex("""@instagram_([a-zA-Z0-9._]{1,30}):""")
    private val TG_REGEX = Regex("""@telegram_(\d{5,15}):""")
    private val SIGNAL_REGEX = Regex("""@signal_(\+?\d{7,15}):""")

    /**
     * Extracts phone number digits from a WhatsApp bot MXID, returning null if it is a LID or invalid.
     */
    fun extractWhatsAppPhone(mxid: String): String? {
        if (WA_LID_REGEX.containsMatchIn(mxid)) return null
        return WA_PHONE_REGEX.find(mxid)?.groupValues?.getOrNull(1)
    }

    /**
     * Extracts username or numeric ID from an Instagram bot MXID.
     */
    fun extractInstagramId(mxid: String): String? {
        return IG_REGEX.find(mxid)?.groupValues?.getOrNull(1)
    }

    /**
     * Extracts Telegram ID from an MXID.
     */
    fun extractTelegramId(mxid: String): String? {
        return TG_REGEX.find(mxid)?.groupValues?.getOrNull(1)
    }

    /**
     * Extracts Signal phone number from an MXID.
     */
    fun extractSignalPhone(mxid: String): String? {
        return SIGNAL_REGEX.find(mxid)?.groupValues?.getOrNull(1)
    }
}
